apiVersion: v1 # API version used for the resource
kind: Service # Resource type (Service in this case)
metadata:
  name: java-docker-service
spec:
  selector:
    app: java-docker 
  type: LoadBalancer # Service type (LoadBalancer in this case)
  ports:
    - name: java-docker 
      port: 8080 # Service port number
      targetPort: 8080 # Target port number in the pods
      protocol: TCP 
